/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SportingEventsIndexRouteImport } from './routes/sportingEvents/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as UsersAddRouteImport } from './routes/users/add'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as SportingEventsAddRouteImport } from './routes/sportingEvents/add'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as AthleteStatsRouteImport } from './routes/athlete/stats'
import { Route as SportingEventsEventIdIndexRouteImport } from './routes/sportingEvents/$eventId.index'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId.edit'
import { Route as SportingEventsEventIdEnrollRouteImport } from './routes/sportingEvents/$eventId.enroll'
import { Route as SportingEventsEventIdEditRouteImport } from './routes/sportingEvents/$eventId.edit'
import { Route as SportingEventsEventIdAthleteIdRouteImport } from './routes/sportingEvents/$eventId.$athleteId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportingEventsIndexRoute = SportingEventsIndexRouteImport.update({
  id: '/sportingEvents/',
  path: '/sportingEvents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersAddRoute = UsersAddRouteImport.update({
  id: '/users/add',
  path: '/users/add',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SportingEventsAddRoute = SportingEventsAddRouteImport.update({
  id: '/sportingEvents/add',
  path: '/sportingEvents/add',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteStatsRoute = AthleteStatsRouteImport.update({
  id: '/athlete/stats',
  path: '/athlete/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SportingEventsEventIdIndexRoute =
  SportingEventsEventIdIndexRouteImport.update({
    id: '/sportingEvents/$eventId/',
    path: '/sportingEvents/$eventId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const SportingEventsEventIdEnrollRoute =
  SportingEventsEventIdEnrollRouteImport.update({
    id: '/sportingEvents/$eventId/enroll',
    path: '/sportingEvents/$eventId/enroll',
    getParentRoute: () => rootRouteImport,
  } as any)
const SportingEventsEventIdEditRoute =
  SportingEventsEventIdEditRouteImport.update({
    id: '/sportingEvents/$eventId/edit',
    path: '/sportingEvents/$eventId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const SportingEventsEventIdAthleteIdRoute =
  SportingEventsEventIdAthleteIdRouteImport.update({
    id: '/sportingEvents/$eventId/$athleteId',
    path: '/sportingEvents/$eventId/$athleteId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/athlete/stats': typeof AthleteStatsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/sportingEvents/add': typeof SportingEventsAddRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/add': typeof UsersAddRoute
  '/settings': typeof SettingsIndexRoute
  '/sportingEvents': typeof SportingEventsIndexRoute
  '/users': typeof UsersIndexRoute
  '/sportingEvents/$eventId/$athleteId': typeof SportingEventsEventIdAthleteIdRoute
  '/sportingEvents/$eventId/edit': typeof SportingEventsEventIdEditRoute
  '/sportingEvents/$eventId/enroll': typeof SportingEventsEventIdEnrollRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/sportingEvents/$eventId': typeof SportingEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/athlete/stats': typeof AthleteStatsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/sportingEvents/add': typeof SportingEventsAddRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/add': typeof UsersAddRoute
  '/settings': typeof SettingsIndexRoute
  '/sportingEvents': typeof SportingEventsIndexRoute
  '/users': typeof UsersIndexRoute
  '/sportingEvents/$eventId/$athleteId': typeof SportingEventsEventIdAthleteIdRoute
  '/sportingEvents/$eventId/edit': typeof SportingEventsEventIdEditRoute
  '/sportingEvents/$eventId/enroll': typeof SportingEventsEventIdEnrollRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/sportingEvents/$eventId': typeof SportingEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/athlete/stats': typeof AthleteStatsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/sportingEvents/add': typeof SportingEventsAddRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/add': typeof UsersAddRoute
  '/settings/': typeof SettingsIndexRoute
  '/sportingEvents/': typeof SportingEventsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/sportingEvents/$eventId/$athleteId': typeof SportingEventsEventIdAthleteIdRoute
  '/sportingEvents/$eventId/edit': typeof SportingEventsEventIdEditRoute
  '/sportingEvents/$eventId/enroll': typeof SportingEventsEventIdEnrollRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/sportingEvents/$eventId/': typeof SportingEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/services'
    | '/unauthorized'
    | '/athlete/stats'
    | '/settings/notifications'
    | '/settings/profile'
    | '/sportingEvents/add'
    | '/users/$userId'
    | '/users/add'
    | '/settings'
    | '/sportingEvents'
    | '/users'
    | '/sportingEvents/$eventId/$athleteId'
    | '/sportingEvents/$eventId/edit'
    | '/sportingEvents/$eventId/enroll'
    | '/users/$userId/edit'
    | '/sportingEvents/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/services'
    | '/unauthorized'
    | '/athlete/stats'
    | '/settings/notifications'
    | '/settings/profile'
    | '/sportingEvents/add'
    | '/users/$userId'
    | '/users/add'
    | '/settings'
    | '/sportingEvents'
    | '/users'
    | '/sportingEvents/$eventId/$athleteId'
    | '/sportingEvents/$eventId/edit'
    | '/sportingEvents/$eventId/enroll'
    | '/users/$userId/edit'
    | '/sportingEvents/$eventId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/services'
    | '/unauthorized'
    | '/athlete/stats'
    | '/settings/notifications'
    | '/settings/profile'
    | '/sportingEvents/add'
    | '/users/$userId'
    | '/users/add'
    | '/settings/'
    | '/sportingEvents/'
    | '/users/'
    | '/sportingEvents/$eventId/$athleteId'
    | '/sportingEvents/$eventId/edit'
    | '/sportingEvents/$eventId/enroll'
    | '/users/$userId/edit'
    | '/sportingEvents/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AthleteStatsRoute: typeof AthleteStatsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SportingEventsAddRoute: typeof SportingEventsAddRoute
  UsersUserIdRoute: typeof UsersUserIdRouteWithChildren
  UsersAddRoute: typeof UsersAddRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SportingEventsIndexRoute: typeof SportingEventsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  SportingEventsEventIdAthleteIdRoute: typeof SportingEventsEventIdAthleteIdRoute
  SportingEventsEventIdEditRoute: typeof SportingEventsEventIdEditRoute
  SportingEventsEventIdEnrollRoute: typeof SportingEventsEventIdEnrollRoute
  SportingEventsEventIdIndexRoute: typeof SportingEventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportingEvents/': {
      id: '/sportingEvents/'
      path: '/sportingEvents'
      fullPath: '/sportingEvents'
      preLoaderRoute: typeof SportingEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/add': {
      id: '/users/add'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof UsersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportingEvents/add': {
      id: '/sportingEvents/add'
      path: '/sportingEvents/add'
      fullPath: '/sportingEvents/add'
      preLoaderRoute: typeof SportingEventsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/stats': {
      id: '/athlete/stats'
      path: '/athlete/stats'
      fullPath: '/athlete/stats'
      preLoaderRoute: typeof AthleteStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportingEvents/$eventId/': {
      id: '/sportingEvents/$eventId/'
      path: '/sportingEvents/$eventId'
      fullPath: '/sportingEvents/$eventId'
      preLoaderRoute: typeof SportingEventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/sportingEvents/$eventId/enroll': {
      id: '/sportingEvents/$eventId/enroll'
      path: '/sportingEvents/$eventId/enroll'
      fullPath: '/sportingEvents/$eventId/enroll'
      preLoaderRoute: typeof SportingEventsEventIdEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportingEvents/$eventId/edit': {
      id: '/sportingEvents/$eventId/edit'
      path: '/sportingEvents/$eventId/edit'
      fullPath: '/sportingEvents/$eventId/edit'
      preLoaderRoute: typeof SportingEventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportingEvents/$eventId/$athleteId': {
      id: '/sportingEvents/$eventId/$athleteId'
      path: '/sportingEvents/$eventId/$athleteId'
      fullPath: '/sportingEvents/$eventId/$athleteId'
      preLoaderRoute: typeof SportingEventsEventIdAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UsersUserIdRouteChildren {
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
}

const UsersUserIdRouteChildren: UsersUserIdRouteChildren = {
  UsersUserIdEditRoute: UsersUserIdEditRoute,
}

const UsersUserIdRouteWithChildren = UsersUserIdRoute._addFileChildren(
  UsersUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AthleteStatsRoute: AthleteStatsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SportingEventsAddRoute: SportingEventsAddRoute,
  UsersUserIdRoute: UsersUserIdRouteWithChildren,
  UsersAddRoute: UsersAddRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SportingEventsIndexRoute: SportingEventsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  SportingEventsEventIdAthleteIdRoute: SportingEventsEventIdAthleteIdRoute,
  SportingEventsEventIdEditRoute: SportingEventsEventIdEditRoute,
  SportingEventsEventIdEnrollRoute: SportingEventsEventIdEnrollRoute,
  SportingEventsEventIdIndexRoute: SportingEventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
